In [16]:
import os
from keras.models import Sequential, load_model
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy
import tensorflow as tf

In [17]:
# seed 값 설정
seed = 0
numpy.random.seed(seed)
tf.set_random_seed(seed)

In [18]:
# 데이터 로드
df = pd.read_csv('../../dataset/sonar.csv', header=None)

dataset = df.values
X = dataset[:, 0:60]
Y_obj = dataset[:, 60]
X, Y_obj

(array([[0.02, 0.0371, 0.0428, ..., 0.0084, 0.009, 0.0032],
        [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
        [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
        ...,
        [0.0522, 0.0437, 0.018, ..., 0.0138, 0.0077, 0.0031],
        [0.0303, 0.0353, 0.049, ..., 0.0079, 0.0036, 0.0048],
        [0.026, 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]], dtype=object),
 array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
        'M', 'M

In [19]:
# Label Encoding
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# 학습셋과 테스트셋의 분리
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)
X_train, X_test, Y_train, Y_test

(array([[0.0135, 0.0045, 0.0051, ..., 0.0028, 0.003, 0.003],
        [0.0293, 0.0644, 0.039, ..., 0.016, 0.0095, 0.0011],
        [0.024, 0.0218, 0.0324, ..., 0.0019, 0.0066, 0.0023],
        ...,
        [0.0228, 0.0106, 0.013, ..., 0.0045, 0.0063, 0.0039],
        [0.0373, 0.0281, 0.0232, ..., 0.0054, 0.0085, 0.006],
        [0.018, 0.0444, 0.0476, ..., 0.005, 0.0073, 0.0022]], dtype=object),
 array([[0.0079, 0.0086, 0.0055, ..., 0.0058, 0.0059, 0.0032],
        [0.0229, 0.0369, 0.004, ..., 0.0029, 0.0104, 0.0163],
        [0.0442, 0.0477, 0.0049, ..., 0.0105, 0.0059, 0.0105],
        ...,
        [0.0315, 0.0252, 0.0167, ..., 0.0035, 0.0001, 0.0055],
        [0.0428, 0.0555, 0.0708, ..., 0.0084, 0.0113, 0.0049],
        [0.0239, 0.0189, 0.0466, ..., 0.0026, 0.0036, 0.0024]],
       dtype=object),
 array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 

In [21]:
# 모델 생성
model = Sequential()
model.add(Dense(24, input_dim=60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=130, batch_size=5)

Epoch 1/130
145/145 [==============================] - 0s 2ms/step - loss: 0.2522 - acc: 0.5310
Epoch 2/130
145/145 [==============================] - 0s 311us/step - loss: 0.2463 - acc: 0.5172
Epoch 3/130
145/145 [==============================] - 0s 329us/step - loss: 0.2440 - acc: 0.5379
Epoch 4/130
145/145 [==============================] - 0s 346us/step - loss: 0.2414 - acc: 0.5379
Epoch 5/130
145/145 [==============================] - 0s 297us/step - loss: 0.2399 - acc: 0.5379
Epoch 6/130
145/145 [==============================] - 0s 321us/step - loss: 0.2374 - acc: 0.5517
Epoch 7/130
145/145 [==============================] - 0s 292us/step - loss: 0.2342 - acc: 0.5379
Epoch 8/130
145/145 [==============================] - 0s 340us/step - loss: 0.2303 - acc: 0.5517
Epoch 9/130
145/145 [==============================] - 0s 327us/step - loss: 0.2176 - acc: 0.6552
Epoch 10/130
145/145 [==============================] - 0s 304us/step - loss: 0.2065 - acc: 0.7034
Epoch 11/130
145/145 

145/145 [==============================] - 0s 348us/step - loss: 0.0672 - acc: 0.9310
Epoch 84/130
145/145 [==============================] - 0s 280us/step - loss: 0.0634 - acc: 0.9310
Epoch 85/130
145/145 [==============================] - 0s 341us/step - loss: 0.0627 - acc: 0.9448
Epoch 86/130
145/145 [==============================] - 0s 298us/step - loss: 0.0628 - acc: 0.9310
Epoch 87/130
145/145 [==============================] - 0s 334us/step - loss: 0.0607 - acc: 0.9379
Epoch 88/130
145/145 [==============================] - 0s 325us/step - loss: 0.0602 - acc: 0.9241
Epoch 89/130
145/145 [==============================] - 0s 305us/step - loss: 0.0571 - acc: 0.9448
Epoch 90/130
145/145 [==============================] - 0s 295us/step - loss: 0.0574 - acc: 0.9448
Epoch 91/130
145/145 [==============================] - 0s 303us/step - loss: 0.0632 - acc: 0.9103
Epoch 92/130
145/145 [==============================] - 0s 293us/step - loss: 0.0546 - acc: 0.9586
Epoch 93/130
145/145 [=

In [22]:
# 모델을 디스크에 저장
model.save('my_model.h5')

In [23]:
# 테스트를 위해 메모르의 모델을 삭제하고 디스크에서 로드한다.
del model
model = load_model('my_model.h5')

In [24]:
print('Test Accuracy: %.4f' % (model.evaluate(X_test, Y_test)[1]))

63/63 [==============================] - 0s 2ms/step
Test Accuracy: 0.8095


In [25]:
# 디스크의 모델을 삭제한다.
os.remove('my_model.h5')